spring.application.name=sagar-jewellery

# Server Config
server.port=${PORT:8080}

# Embedded Tomcat Optimization for High Concurrency (100k users scale)
server.tomcat.threads.max=800
server.tomcat.threads.min-spare=100
server.tomcat.max-connections=20000
server.tomcat.accept-count=1000

# OpenAPI Config (Swagger)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# App Config
spring.main.allow-circular-references=true

spring.profiles.active=${ENV:dev}