spring.application.name=sagar-jewellery

# Server Config
server.port=${PORT:8080}

# OpenAPI Config (Swagger)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# App Config
spring.main.allow-circular-references=true

spring.profiles.active=${ENV:dev}